version: '3.1'
services:
  minio:
    image: quay.io/minio/minio
    networks:
      - airflow
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ${PWD}/include/minio:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    restart: always
    env_file: .env
    
  streamlit:
    image: python:3.9
    command: bash -c "pip install -r /app/include/streamlit_container_requirements.txt && streamlit run --server.enableWebsocketCompression=false --server.enableCORS=false --server.enableXsrfProtection=false /app/include/streamlit_app.py"
    ports:
      - "8501:8501"
    volumes:
      - ./include:/app/include
  scheduler:
    extra_hosts:
      - "host.docker.internal:host-gateway"
  webserver:
    extra_hosts:
      - "host.docker.internal:host-gateway"
  triggerer:
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    extra_hosts:
      - "host.docker.internal:host-gateway" 